version: 2

defaults: &defaults


# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
anchors:
  android_docker: &android_docker
    docker:
      - image: circleci/android:api-29
  android_enviroment: &android_enviroment
    enviroment:
      JVM_OPS: -Xmx3200m
  steps:
    - cashe_key: &cashe_key jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}


jobs:
  build:
    <<: *android_docker
    <<: *android_enviroment
    steps:
      - checkout
      - restore_cache:
          key: *cashe_key
      - run:
          name: Download dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: *cashe_key
      - run:
          name: Build APK
          command: ./gradlew assembleDebug
      - persist_to_workspace:
          root: .
          paths:
            - .
  # lint:
  #   <<: *android_docker
  #   <<: *android_enviroment
  #   steps:
  #     - attach_workspace:
  #         at: .
  #     - run:
  #         name: Check lint
  #         command: ./gradlew lintProductDebug
  #     - store_artifacts:
  #         path: app/build/reports
  #         destination: reports
  # deploy:
  #   <<: *android_docker
  #   <<: *android_enviroment
  #   steps:
  #     - attach_workspace:
  #         at: .
  #     - run:
  #         name: Upload DeployGate
  #         command: curl -F "token={TOKEN}" -F "file=@{FILE}" -F "message={MESSAGE}" https://deploygate.com/api/users/{NAME}/apps

workflows:
  version: 2
  build_deploy:
    jobs:
      - build
      # - lint:
      #     requires:
      #       - build
      - deploy:
          requires:
            - build
            # - lint
          filters:
            branches:
              only: develop